version: '3.7'

services:
  db:
    image: pbc6835/todo-flask-mongodb:v1.0.0
    networks:
      - todo_net
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  todo:
    image: pbc6835/todo-flask-project:v1.0.0
    ports:
      - "5000:5000"
    networks:
      - todo_net
    environment:
      - DB_URL=mongodb://db:27017
      - DEBUG=app:*
    
networks:
  todo_net:

volumes:
  dbdata:
