apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mongodb
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
      tier: mongodb
  template:
    metadata:
      labels:
        app: todo
        tier: mongodb
    spec:
      containers:
        - image: pbc6835/todo-flask-mongodb
          name: mongodb
          ports:
            - containerPort: 3306
              name: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: todo-mongodb
  labels:
    app: todo
spec:
  ports:
    - port: 3306
  selector:
    app: todo
    tier: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
      tier: frontend
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
        - image: pbc6835/todo-flask-project
          name: todo
          ports:
            - containerPort: 80
              name: todo

---
apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    app: todo
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: todo
    tier: frontend
