version: '3.7'

services:
  db:
    image: qudtjr0409/another_web:1.0
    ports:
      - "4000:4000"
    volumes:
      - .:/database
    networks:
      - some_net

  web:
    image: qudtjr0409/simple_web:1.0
    ports:
      - "3000:3000"
    volumes:
      - .:/database
    networks:
      - some_net
    
networks:
  some_net:
    driver: bridge

volumes:
  database:
    driver: local